 port = ":80"
 graceTimeOut = 10
 logLevel = "INFO"
 
 defaultEntryPoints = ["http", "https"]
 entryPoint = "http"
 
 [entryPoints]
   [entryPoints.http]
   address = ":8000"
 
 [web]
 address = ":8081"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "tty0.in"
watch=true
