port = ":80"
graceTimeOut = 10
logLevel = "INFO"

defaultEntryPoints = ["http"]
entryPoint = "http"

[entryPoints]
  [entryPoints.http]
  address = ":8000"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "test@traefik.io"
storageFile = "acme.json"
onDemand = true
caServer = "https://acme-staging.api.letsencrypt.org/directory"
entryPoint = "https"

[[acme.domains]]
  main = "local1.com"
  sans = ["test1.local1.com", "test2.local1.com"]
  
[web]
address = ":8081"
watch = true

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true

